version: '2.2'
services:
  ubuntuweb83:
    image: orangehrm/dev-environment:ubuntu24.04-php8.3-latest
    ports:
      - "9283:443"
    volumes:
      - ./html:/var/www/html
      - ./custom-compose/config/ubuntuweb83/apache2/sites-available:/etc/apache2/sites-available
      - ./custom-compose/config/ubuntuweb83/apache2/sites-enabled:/etc/apache2/sites-enabled
      - ./custom-compose/config/ubuntuweb83/apache2/cert:/etc/apache2/cert
      - ./custom-compose/config/ubuntuweb83/apache2/conf.d/apache2.conf:/etc/apache2/apache2.conf
      - ./custom-compose/logs/apache_logs/ubuntuweb83:/var/log/apache2/ubuntuweb83
      - ./custom-compose/config/ubuntuweb83/php/cli-php.ini:/etc/php/8.3/cli/php.ini
      - ./custom-compose/config/ubuntuweb83/php/apache2-php.ini:/etc/php/8.3/apache2/php.ini
      - /etc/localtime:/etc/localtime
    privileged: true    
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.0.183
    restart: always
    container_name: dev_web_83_ubuntu